### ISSUE TITLE
[Front-end] Implement Log in page

### ISSUE THREAD

**Issue by sebastien-blain** [Talos10/SOEN390-team-9#12]
## Description
As a user, I want to be able to log in in the application so that I can use it.

### Overview
Create Log in page to log in a registered account using an email and a password.

Store the token received from the response request when the account is successfully logged in.

### Acceptance criteria
- [ ] Unit-tests are passing
- [ ] Given the email and password are valid, the user can access the application.
- [ ] Given the email or password is not valid, the user receives an error and cannot access the application.

**Comment by tjosepo** [comment]
Proposed Mockup: https://www.figma.com/file/VMLY38N09kTVQ1jLLEcZw5/Mockups?node-id=15%3A687
