### ISSUE TITLE
[Bug] - Too many connection for database

### ISSUE THREAD

**Issue by sebastien-blain** [Talos10/SOEN390-team-9#124]
After interacting with the app, we get an error that there is too mny connection to the database.

To resolve: end the db connection at the end of each query

**Comment by tjosepo** [comment]
Here's the hotfix I'll be using while coding. I don't think it's a good long term solution if we still want to retry the connection when it drops, but it's a good temporary fix.

```js
// inside dbConnections.ts

let connection: any;
const db = () => {
    connection = connection ?? get_connection();
    return connection;
};

export default db; 
```
