### ISSUE TITLE
[Wireframe] Admin Page UI

### ISSUE THREAD

**Issue by sebastien-blain** [Talos10/SOEN390-team-9#33]
## Description
As a dev, I want to be able to see a UI estimate of the Admin page.

### Overview
Research UI design trends and define user experience goals.

Investigate the specific requirements required.

Design the wireframe for the Admin page on Figma.

### Acceptance criteria
- [ ] Wireframe is designed using the project style.
- [ ] The mockup is accepted by the majority of the group.

**Comment by tjosepo** [comment]
**Admin Page: Accounts Management:**
https://www.figma.com/file/VMLY38N09kTVQ1jLLEcZw5/ERP-Software-Mockups?node-id=110%3A609
