### ISSUE TITLE
Item information doesn't appear when we click on an item

### ISSUE THREAD

**Issue by sebastien-blain** [Talos10/SOEN390-team-9#99]

**Comment by tjosepo** [comment]
@sebastien-blain Does the backend support editing existing items? If yes, I will use the [Edit Item mockup](https://www.figma.com/file/VMLY38N09kTVQ1jLLEcZw5/ERP-Software-Mockups?node-id=207%3A0) I made. Else, I'll probably create a new mockup to display the item information in a read-only way.

**Comment by sebastien-blain** [comment]
@tommy-josepovic I think we decided not to be able to modify the items. So we shouldn't need an edit item page. 
I'm currently working on displaying the items information by using a collapsible table inside the inventory page. That way you click on an item in the inventory and the table "expands". 
A bit like this: https://material-ui.com/components/tables/#collapsible-table

Let me know what you think.
